[tool.black]
line-length = 72

[tool.flake8]
max-line-length = 72
exclude = ['venv','test_script.py']

[tool.isort]
profile = "black" 
line_length = 72
skip = ["env", "venv", ".venv", "build", "dist"]