name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    name: Test with Github Actions 🚀
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up virtual environment & install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Sort imports with isort
        run: |
         pip install isort
         isort . --profile black --line-length=72 --skip='venv'

      - name: Run black
        run: |
          pip install black
          black . --check --line-length=72

      - name: Lint with flake8
        run: |
         pip install flake8
         flake8 . --max-line-length=100 --ignore=E128,W503 --exclude=venv
